trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Dev
    displayName: "Build and Deploy to Dev"
    jobs:
      - template: templates/build-and-deploy-template.yml
        parameters:
          environment: "dev"
          acrLoginServer: "ACR-Login-Server"
          imageTag: "dev"

  - stage: Staging
    displayName: "Build and Deploy to Staging"
    dependsOn: Dev
    jobs:
      - template: templates/build-and-deploy-template.yml
        parameters:
          environment: "staging"
          acrLoginServer: "ACR-Login-Server"
          imageTag: "staging"

  - stage: Prod
    displayName: "Build and Deploy to Prod"
    dependsOn: Staging
    jobs:
      - template: templates/build-and-deploy-template.yml
        parameters:
          environment: "prod"
          acrLoginServer: "ACR-Login-Server"
          imageTag: "prod"